### ISSUE TITLE
Ask follow-up questions

### ISSUE THREAD

**Issue by adamjonas** [bitcoinsearch/chat-btc#42]
As a learner, I should be presented with a list of follow-up questions to further explore the subject of my question below the references.

(Prompt engineering concern)

**Comment by aassoiants** [comment]
UI inspiration from [here](https://www.delphi.ai/jameson-lopp/talk)

![image](https://github.com/bitcoinsearch/chat-btc/assets/126297088/3b82bae8-5bf0-4d11-85e6-7fd5e0a20f2a)

**Comment by IgboPharaoh** [comment]
#63
