### ISSUE TITLE
Prevent from generating sources when unable to properly answer a question

### ISSUE THREAD

**Issue by aassoiants** [bitcoinsearch/chat-btc#47]
See image for example
![image](https://github.com/bitcoinsearch/chat-btc/assets/126297088/44c1f53d-8b87-40ff-96f3-e4443e31d33c)

**Comment by kouloumos** [comment]
@Emmanuel-Develops is this still an issue?

**Comment by Emmanuel-Develops** [comment]
> @Emmanuel-Develops is this still an issue?

yes it is. Looking into it
