### ISSUE TITLE
Replace document limits with token limit

### ISSUE THREAD

**Issue by Emmanuel-Develops** [bitcoinsearch/chat-btc#68]
We currently use some arbitrary document limits like number of documents and a cap on each document length.
This is not ideal for 2 reasons:
- It doesn't factor into consideration numerous small documents
- It breaks up larger documents at an arbitrary character count without factoring the rest of the sources.

**Comment by kouloumos** [comment]
This [was closed](https://github.com/bitcoinsearch/chat-btc/pull/64#issuecomment-1994908006) by #64. 
>closes https://github.com/bitcoinsearch/chat-btc/issues/68
Implemented an input token enforcer to limit the input tokens sent to chat to 7000 (with avg of 0.75 token/word which is about 9333 words).
>
> Should be a separate PR but I'd like it if we get it out in this PR due to the refactoring made in

@Emmanuel-Develops, you used the "closes X" syntax, but in order for GitHub to pick it automatically you must edit the PR description and add it there.
