### ISSUE TITLE
Improving Umami Analytics for Better Insight on Author Engagement

### ISSUE THREAD

**Issue by kouloumos** [bitcoinsearch/chat-btc#74]
We're currently leveraging [umami](https://visits.bitcoindevs.xyz/share/O3RcrKXLglJyaXX8/chat-btc) as a privacy-friendly analytics tool to gather insights for chat-btc. However, due to the site's structure, where changes are made via URL parameters on a single root page, the depth of insights we can gather is limited. Specifically, we're missing out on valuable data regarding how users interact with different authors on the site. For instance, author selection is a significant interaction that's currently invisible to our analytics because it's appended as a parameter in the URL (e.g., `/?author=holocat`), which umami cannot track.

To address this and enhance our understanding of user engagement with authors, I propose two potential solutions:
- **Create Separate Pages for Each Author**: By setting up dedicated pages (e.g., `/holocat`, `/murch`), we could easily track how users engage with individual authors. This approach would require some adjustments in how we handle routing and author selection, moving from URL parameters to a page-based system. While this requires a bit of work, it's not overly complex and offers a cleaner analytics insight.
- **Implement Tracking Events**: A simpler and more straightforward solution would be to add a tracking event that captures author selections. This method would involve a minimal change, essentially just one line of code, to integrate [umami's event tracking function](https://umami.is/docs/track-events).

Both solutions aim to provide us with more detailed analytics without being invasive or compromising user privacy. This enhancement will allow us to better understand user preferences and interactions with authors, ultimately helping us improve the experience.

**Comment by Extheoisah** [comment]
*Update on this issue*
@Emmanuel-Develops discovered we're tracking some user queries as shown here https://visits.bitcoindevs.xyz/share/O3RcrKXLglJyaXX8/chat-btc?view=query
So one can see the metrics such as authors, questions as well as frequency of queries.

Feel free to close this issue if this suffices.
